Add jinx run-in command

diff --git a/jinx b/jinx
--- a/jinx
+++ b/jinx
@@ -68,6 +68,7 @@ cmd_help() {
     printf "\n   reinstall          Reinstalls package(s)"
     printf "\n   dry-run            Prints all packages that need to be built in order (space separated)"
     printf "\n   download           Downloads pre-built package(s) from remote repo"
+    printf "\n   run-in             Runs a command in a container prepared with a recipe's hostdeps"
     printf "\n   rebuild-cache      Rebuilds Jinx cache"
     printf "\n\nexample: $0 update '*'\n"
 }
@@ -1752,6 +1753,84 @@ cmd_regen() {
     done
 }
 
+do_run_in() {
+    pkg="$1"
+    cmd_file="$2"
+
+    include_recipe "${base_dir}"/recipes/${pkg}
+
+    mkdir -p "${build_dir}"/builds/${name}
+
+    if ! [ -z "${from_source}" ] || ! [ -z "${tarball_url}" ] || ! [ -z "${git_url}" ] || ! [ -z "${source_dir}" ]; then
+        if ! [ -z "${from_source}" ]; then
+            version=$(unset version && source_source_recipe ${from_source} && echo "$version")
+            source_dir="$(unset source_dir && source_source_recipe ${from_source} && echo "$source_dir")"
+        else
+            from_source=${name}
+        fi
+
+        if [ -z "${source_dir}" ]; then
+            source_dir="${base_dir}"/sources/${from_source}
+        else
+            source_dir="${base_dir}"/"${source_dir}"
+        fi
+    fi
+
+    prefix="/usr"
+    sysroot_dir="/sysroot"
+
+    cd "${build_dir}"/builds/${name}
+
+    set --
+    . "${cmd_file}"
+}
+
+cmd_run_in() {
+    if [ -z "$1" ]; then
+        die "$0: run-in requires a recipe name"
+    fi
+    run_in_recipe="$1"
+    shift 1
+    if [ -z "$1" ]; then
+        die "$0: run-in requires a command to run"
+    fi
+
+    if ! [ -f "${base_dir}"/recipes/${run_in_recipe} ]; then
+        die "$0: recipe '${run_in_recipe}' not found"
+    fi
+
+    include_recipe "${base_dir}"/recipes/${run_in_recipe}
+
+    if ! [ -z "${from_source}" ]; then
+        tracked_subshell 'do_source "${from_source}"'
+    else
+        tracked_subshell 'do_source "${name}"'
+    fi
+
+    make_temp
+    cmd_file="${tmp}"
+    {
+        printf 'exec'
+        for arg in "$@"; do
+            escaped=$(printf '%s' "$arg" | sed 's/\\/\\\\/g; s/"/\\"/g; s/`/\\`/g')
+            printf ' "%s"' "$escaped"
+        done
+        printf '\n'
+    } >"${cmd_file}"
+    cmd_file_inner="/base_dir/.jinx-cache/tmp/$(basename "${cmd_file}")"
+
+    prepare_container
+
+    mkdir -p "${build_dir}"/builds/${name}
+
+    unset container_sources_ro
+    unset container_base_dir_ro
+    allow_network="yes"
+    run_in_container internal-run-in "${run_in_recipe}" "${cmd_file_inner}"
+
+    destroy_container
+}
+
 cmd_host_rebuild() {
     for ppkg in "$@"; do
         for pkg in $(eval '(' cd "'${base_dir}'"/host-recipes '&&' echo "${ppkg}" ')' ); do
@@ -2104,6 +2183,10 @@ case "$1" in
     internal-package)
         do_package "$2"
         ;;
+    internal-run-in)
+        shift 1
+        do_run_in "$@"
+        ;;
     host-build)
         shift 1
         cmd_host_build "$@"
@@ -2146,6 +2229,10 @@ case "$1" in
     download)
         shift 1
         cmd_download "$@"
+        ;;
+    run-in)
+        shift 1
+        cmd_run_in "$@"
         ;;
     *)
         die "$0: unknown command: $1"
