Verify xbps b2sum

diff --git a/jinx b/jinx
--- a/jinx
+++ b/jinx
@@ -41,6 +41,7 @@ jinx_version="${jinx_major_ver}.${jinx_minor_ver}"
 debian_snapshot="20250401T023134Z"
 
 XBPS_VERSION=0.59.2
+XBPS_B2SUM=cabe5676eb1611271f255c75f4439f3ef4ea6096d6fc26f0982da471556e1fd1733cb76a6d5857d3546513b157e8a3493624d09d989134f3f6d7763c55e98a83
 
 die() {
     echo "$1"
@@ -1896,6 +1897,9 @@ Acquire::Check-Valid-Until "0";' >> "$JINX_CACHE_DIR/sets/.image/etc/apt/apt.con
     XBPS_BUILDENV="$JINX_CACHE_DIR/xbps_buildenv"
     cp -Pprf "$JINX_CACHE_DIR/sets/.image/." "${XBPS_BUILDENV}/"
     curl -Lo "${XBPS_BUILDENV}/xbps-${XBPS_VERSION}.tar.gz" https://github.com/void-linux/xbps/archive/refs/tags/${XBPS_VERSION}.tar.gz
+    if ! "$JINX_CACHE_DIR/b2sum" "${XBPS_BUILDENV}/xbps-${XBPS_VERSION}.tar.gz" | grep "${XBPS_B2SUM}" >/dev/null 2>&1; then
+        die "Jinx: Failed to verify XBPS tarball"
+    fi
     ( cd "${XBPS_BUILDENV}" && gunzip < xbps-${XBPS_VERSION}.tar.gz | tar -xf - )
     run_in_container1 "${XBPS_BUILDENV}" apt-get install -y build-essential pkg-config zlib1g-dev libssl-dev libarchive-dev
     # XXX: xbps upstream forgot to bump version string
