display errors on xbps-install

diff --git a/jinx b/jinx
--- a/jinx
+++ b/jinx
@@ -561,10 +561,15 @@ prepare_container() {
     make_temp -d
     sysroot_dir="${tmp}"
 
+    make_temp
+    tmp_stdout="${tmp}"
+    make_temp
+    tmp_stderr="${tmp}"
     for dep in $(cat "${deps_file}"); do
         XBPS_ARCH=invalid \
         XBPS_TARGET_ARCH="${JINX_ARCH}" \
-            xbps-install -y -r "${sysroot_dir}" -R "${build_dir}"/pkgs "${dep}" >/dev/null 2>&1
+		xbps-install -y -r "${sysroot_dir}" -R "${build_dir}"/pkgs "${dep}" >"${tmp_stdout}" 2>"${tmp_stderr}" \
+	|| (echo "jinx: xbps-install failed! stdout:" && sed 's/^/\- /' "${tmp_stdout}" && echo jinx: stderr: && sed 's/^/\- /' "${tmp_stderr}" && exit 17)
     done
 
     if [ "$JINX_NATIVE_MODE" = "yes" ] && [ -z "$cross_compile" ]; then
