Add workaround for broken images

diff --git a/jinx b/jinx
--- a/jinx
+++ b/jinx
@@ -195,6 +195,14 @@ EOF
 }
 
 run_in_container() {
+    local image_id
+
+    image_id=$(docker build -q "${dockerfile_dir}" || echo "failed")
+    if [ "$image_id" = "failed" ]; then
+        echo "* cached image causing issues, trying clean..."
+        image_id=$(docker build -q --no-cache "${dockerfile_dir}")
+    fi
+
     docker run --rm \
         --user=$(id -u):$(id -g) \
         -v "${container_pkgs}":/usr/local \
@@ -202,7 +210,7 @@ run_in_container() {
         -v "${script_dir}":/jinx \
         -v "${base_dir}":/base_dir \
         -w /base_dir \
-        $(docker build -q "${dockerfile_dir}") \
+        ${image_id} \
         /jinx/${script_name} $1 $2 $3 $4 $5
 }
 
