Move to the user the burden of picking Debian snapshot and base packages

diff --git a/jinx b/jinx
--- a/jinx
+++ b/jinx
@@ -33,12 +33,10 @@ export LC_COLLATE
 
 umask 0022
 
-jinx_major_ver="0.7"
-jinx_minor_ver="11"
+jinx_major_ver="0.8"
+jinx_minor_ver="0"
 
 jinx_version="${jinx_major_ver}.${jinx_minor_ver}"
-
-debian_snapshot="20251020T082908Z"
 
 XBPS_VERSION=213c8290ceca38264d2907d6d01f91775951bd14
 XBPS_SHA256SUM=6c4420c86212be203cdbc061ab2e53255f6407e15b7aee307eac2a8f370eb3c4
@@ -260,8 +258,6 @@ include_recipe() {
     unset bootstrap_pkg
     unset from_source
     unset source_dir
-    unset hg_url
-    unset tag
     unset git_url
     unset commit
     unset shallow
@@ -707,11 +703,6 @@ destroy_container() {
     rm -rf "${container_pkgs}" "${sysroot_dir}"
 }
 
-do_hg_fetch() {
-    hg clone "${hg_url}" "${base_dir}"/sources/${name}
-    ( cd "${base_dir}"/sources/${name} && hg up "${tag}" )
-}
-
 do_git_fetch() {
     if [ -z "${commit}" ]; then
         die "* error: Git commit not specified"
@@ -791,7 +782,7 @@ get_real_source_dir() {
     unset is_local_package
     unset is_sourceless_package
 
-    if [ -z "${source_dir}" ] && [ -z "${git_url}" ] && [ -z "${hg_url}" ] && [ -z "${tarball_url}" ]; then
+    if [ -z "${source_dir}" ] && [ -z "${git_url}" ] && [ -z "${tarball_url}" ]; then
         source_dir=/dev/null
         is_local_package=true
         is_sourceless_package=true
@@ -834,8 +825,6 @@ do_fetch() {
     if ! [ "${is_local_package}" = true ] && ! [ "${is_sourceless_package}" = true ]; then
         if ! [ -z "${git_url}" ]; then
             do_git_fetch
-        elif ! [ -z "${hg_url}" ]; then
-            do_hg_fetch
         elif ! [ -z "${tarball_url}" ]; then
             do_tarball_fetch
         fi
@@ -999,7 +988,7 @@ do_configure() {
 
     mkdir -p "${build_dir}"/builds/${name}
 
-    if ! [ -z "${from_source}" ] || ! [ -z "${tarball_url}" ] || ! [ -z "${git_url}" ] || ! [ -z "${hg_url}" ] || ! [ -z "${source_dir}" ]; then
+    if ! [ -z "${from_source}" ] || ! [ -z "${tarball_url}" ] || ! [ -z "${git_url}" ] || ! [ -z "${source_dir}" ]; then
         if ! [ -z "${from_source}" ]; then
             version=$(unset version && source_source_recipe ${from_source} && echo "$version")
             source_dir="$(unset source_dir && source_source_recipe ${from_source} && echo "$source_dir")"
@@ -1027,7 +1016,7 @@ do_build() {
 
     mkdir -p "${build_dir}"/builds/${name}
 
-    if ! [ -z "${from_source}" ] || ! [ -z "${tarball_url}" ] || ! [ -z "${git_url}" ] || ! [ -z "${hg_url}" ] || ! [ -z "${source_dir}" ]; then
+    if ! [ -z "${from_source}" ] || ! [ -z "${tarball_url}" ] || ! [ -z "${git_url}" ] || ! [ -z "${source_dir}" ]; then
         if ! [ -z "${from_source}" ]; then
             version=$(unset version && source_source_recipe ${from_source} && echo "$version")
             source_dir="$(unset source_dir && source_source_recipe ${from_source} && echo "$source_dir")"
@@ -1058,7 +1047,7 @@ do_package() {
     rm -rf "${dest_dir}"
     mkdir -p "${dest_dir}"
 
-    if ! [ -z "${from_source}" ] || ! [ -z "${tarball_url}" ] || ! [ -z "${git_url}" ] || ! [ -z "${hg_url}" ] || ! [ -z "${source_dir}" ]; then
+    if ! [ -z "${from_source}" ] || ! [ -z "${tarball_url}" ] || ! [ -z "${git_url}" ] || ! [ -z "${source_dir}" ]; then
         if ! [ -z "${from_source}" ]; then
             version=$(unset version && source_source_recipe ${from_source} && echo "$version")
             source_dir="$(unset source_dir && source_source_recipe ${from_source} && echo "$source_dir")"
@@ -1187,9 +1176,6 @@ do_regen() {
         if ! [ -z "${git_url}" ]; then
             mv $1-clean/.git "${vc_dir_clean}"
             mv $1-workdir/.git "${vc_dir_workdir}"
-        elif ! [ -z "${hg_url}" ]; then
-            mv $1-clean/.hg "${vc_dir_clean}"
-            mv $1-workdir/.hg "${vc_dir_workdir}"
         fi
 
         git diff --no-index --no-prefix $1-clean $1-workdir >"${patch_file}" || true
@@ -1197,9 +1183,6 @@ do_regen() {
         if ! [ -z "${git_url}" ]; then
             mv "${vc_dir_clean}" $1-clean/.git
             mv "${vc_dir_workdir}" $1-workdir/.git
-        elif ! [ -z "${hg_url}" ]; then
-            mv "${vc_dir_clean}" $1-clean/.hg
-            mv "${vc_dir_workdir}" $1-workdir/.hg
         fi
 
         if [ -s "${patch_file}" ]; then
@@ -1835,7 +1818,7 @@ EOF
         mount --bind '${apt_cache}' '$JINX_CACHE_DIR/sets/.image/var/cache/apt/archives'
 
         LD_PRELOAD='$JINX_CACHE_DIR/sets/.image/nochown.so' debootstrap \
-            --foreign sid '$JINX_CACHE_DIR/sets/.image' https://snapshot.debian.org/archive/debian/${debian_snapshot}/
+            --foreign sid '$JINX_CACHE_DIR/sets/.image' https://snapshot.debian.org/archive/debian/${JINX_DEBIAN_SNAPSHOT}/
     "
 
     for dir in dev proc sys run tmp var/tmp; do
@@ -1863,7 +1846,7 @@ Acquire::Check-Valid-Until "0";' >> "$JINX_CACHE_DIR/sets/.image/etc/apt/apt.con
         chmod 755 "$f"
     done
 
-    run_in_container1 "$JINX_CACHE_DIR/sets/.image" apt-get install -y autopoint bash bison bzip2 cmake curl diffutils docbook-xsl doxygen file findutils flex gawk gettext git grep gzip lzip m4 make mercurial meson ninja-build patch perl python3 sed tar texinfo w3m which xmlto xsltproc xz-utils zstd
+    run_in_container1 "$JINX_CACHE_DIR/sets/.image" apt-get install -y bash bzip2 curl diffutils findutils gawk git grep gzip lzip patch sed tar xz-utils zstd ${JINX_BASE_PACKAGES}
 
     if ! [ -z "${JINX_CMAKE_PLATFORM}" ]; then
         cp "${base_dir}/${JINX_CMAKE_PLATFORM}" "${JINX_CACHE_DIR}"/sets/.image/usr/share/cmake-*/Modules/Platform/
@@ -1893,15 +1876,22 @@ if ! [ -f "$JINX_CONFIG_FILE" ]; then
     die "$0: missing Jinxfile in directory '$base_dir'"
 fi
 
+unset JINX_MAJOR_VER
+unset JINX_DEBIAN_SNAPSHOT
+unset JINX_BASE_PACKAGES
 unset JINX_CMAKE_PLATFORM
 . "${JINX_CONFIG_FILE}"
 
-if [ -z "$JINX_MAJOR_VER" ]; then
-    die "$0: required config variable \$JINX_MAJOR_VER missing"
+if [ -z "${JINX_MAJOR_VER}" ]; then
+    die "$0: required Jinxfile variable JINX_MAJOR_VER missing"
 fi
 
 if ! [ "$JINX_MAJOR_VER" = "$jinx_major_ver" ]; then
     die "$0: needed major version ($JINX_MAJOR_VER) differs from Jinx-provided major version ($jinx_major_ver)"
+fi
+
+if [ -z "${JINX_DEBIAN_SNAPSHOT}" ]; then
+    die "$0: required Jinxfile variable JINX_DEBIAN_SNAPSHOT missing"
 fi
 
 if [ -z "$JINX_ARCH" ]; then
